apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: nginx-cip
  name: nginx-cip
  namespace: nginx-app
spec:
  ports:
  - name: 8383-80
    port: 8383
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx
  type: ClusterIP
status:
  loadBalancer: {}
