apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: nginx-np
  name: nginx-np
  namespace: nginx-app
spec:
  ports:
  - name: 8484-80
    port: 8484
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx
  type: NodePort
status:
  loadBalancer: {}
